services:
  localstack:
    image: localstack/localstack:4.14.0
    container_name: localstack_sandbox
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
      - ECR_ENDPOINT_STRATEGY=off
      - SIMULATION_BUCKET_NAME=${SIMULATION_BUCKET_NAME:-my-test-bucket}
    volumes:
      - ./init-hooks:/etc/localstack/init/ready.d
      - "/var/run/docker.sock:/var/run/docker.sock"

  local-registry:
    image: registry:2
    container_name: local_docker_registry
    ports:
      - "127.0.0.1:5001:5000"
